server:
  port: 80

spring:
  thymeleaf:
    cache: false #关闭thymeleaf缓存


# spring security认证可配置化
mengxuegu:
  security:
    authentication:
      loginPage: /login/page # 响应认证请求（自定义登录页面）
      loginProcessingUrl: /login/form # 登录页面表单提交的URL
      usernameParameter: name # 登录页面表单用户名的属性名
      passwordParameter: pwd # 登录页面表单密码的属性名
      staticPaths: # 认证拦截所有请求，释放静态资源文件地址："/dist/**","/modules/**","/plugins/**"
        - /dist/**
        - /modules/**
        - /plugins/**
      loginType: REDIRECT