server:
  port: 80

spring:
  thymeleaf:
    cache: false #关闭thymeleaf缓存

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource           # 当前数据源操作类型
    username: root
    password: yuyue520
    url: jdbc:mysql://47.104.107.189:33306/study-security?serverTimezone=GMT%2B8  # 数据库名称
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间

# spring security认证可配置化
mengxuegu:
  security:
    authentication:
      loginPage: /login/page # 响应认证请求（自定义登录页面）
      loginProcessingUrl: /login/form # 登录页面表单提交的URL
      usernameParameter: name # 登录页面表单用户名的属性名
      passwordParameter: pwd # 登录页面表单密码的属性名
      staticPaths: # 认证拦截所有请求，释放静态资源文件地址："/dist/**","/modules/**","/plugins/**"
        - /dist/**
        - /modules/**
        - /plugins/**
      loginType:  # 定义成功失败处理器返回的方式